- cmd/gen-go-sample/inittree.go
- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/test.bash
- cmd/gen-go-sample/testdata/sample.want
- internal/gengapic/example.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/pbinfo/pbinfo.go
Previously we imported the gRPC client, not the GAPIC client
> sample: properly import client package

- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/testdata/sample.want
including copyright and imports.
> sample: test whole file

- cmd/gen-go-sample/gapic.go
- cmd/gen-go-sample/inittree.go
- cmd/gen-go-sample/inittree_test.go
- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/testdata/sample.want
Only strings work for now and argument names are bad.
We can fix this in a follow up.
> sample: accept CLI arguments

- cmd/gen-go-sample/main_test.go
- internal/gengapic/client_init_test.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic_test.go
- internal/txtdiff/diff.go
This makes reading test failures a lot easier.
> test: properly diff the text

- cmd/gen-go-sample/gapic.go
- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/out.go
- cmd/gen-go-sample/test.bash
- cmd/gen-go-sample/testdata/sample.want
and handle multiple files too.
> sample: handle loops in output

- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/testdata/sample_empty.want
- cmd/gen-go-sample/testdata/sample_paging.want
- cmd/gen-go-sample/testdata/sample_unary.want
> sample: indent request initialization

- Dockerfile
- README.md
- gapic.sh
* changes `gapic.sh` docker shortcut to use expose the generic `--options` flag
* changes plugin options environment variable for the image to generic `PLUGIN_OPTIONS`
* update README Docker Wrapper section
> make gapic shortcut expose generic options flag

- showcase/go.mod
- showcase/go.sum
- utils/showcase.bash
* update to gapic-showcase v0.0.12
* gapic-showcase binary download respects GOHOSTOS/ARCH
> Showcase v0.0.12

- internal/gengapic/gengapic.go
- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
This PR adds support for markdown lists in proto comments for rendering in the gapic
> add comment markdown list support

- go.mod
- go.sum
- showcase/go.mod
- showcase/go.sum
Bump protobuf dependency version to v1.3.0
> protobuf version to v1.3.0

- .gitignore
Resolves #110 
This pull request aims to add specific idea and swap file of jetbrains and vim IDEs into gitignore.
> Modify gitignore with respect to IDEs

- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
> gapic: add Heading(Open/Close) to md render

- internal/gengapic/client_init.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/host_port_opt.want
> gapic: add WithDisableServiceConfig to default opts

- docker-entrypoint.sh
> chore: expose grpc-service-config opt to Docker entrypoint

- test.sh
* add texttospeech to generation test script
> chore: add fully annotated/configd api to tests

- internal/gensample/genmanifest.go
- internal/gensample/testdata/manifest.want
Based on issues found during regenerating samples.
> SampleGen: Fix manifest file

- cmd/gen-go-sample/README.md
Remove the extra `-desc` flag.
> fix invocation in samplegen readme

- README.md
- repositories.bzl
- rules_go_gapic/go_gapic.bzl
* update gapic-generator dependency
* update README with optional attributes
Tested locally (going to add bazel testing to CI per #236).
> bazel: add service_yaml attribute

- internal/gengapic/lro.go
- internal/gengapic/testdata/method_EmptyLRO.want
> gapic: fix LRO Poll handling of google.protobuf.Empty

- internal/gengapic/doc_file.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
Fixes a comment from https://code-review.googlesource.com/c/gocloud/+/49730
> gapic: fix package doc comment

- repositories.bzl
Update of Go deps based on `go.mod` using some manual editing after:
`bazel run //:gazelle -- update-repos -from_file=go.mod`
> chore: update bazel repositories.bzl

- internal/gengapic/lro.go
- rules_go_gapic/go_gapic_repositories.bzl
bazel: add gax v1 as a go_gapic_repository
gapic: remove unused import for LRO Empty response
> chores: remove extraneous gen'd import and add missing dep to go_gapic_repositories

- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
> gapic: fix softbreaks in html link tags

- renovate.json
Reverts googleapis/gapic-generator-go#372
> Revert "chore: renovatebot rebase when behind"

- renovate.json
> chore: add genproto schedule, rebase config, and automerge label

- showcase/README.md
Adds a README to the showcase integration testing submodule.
> chore: add showcase integration test readme

- .github/sync-repo-settings.yaml
Update repo-settings config with new required checks to prevent them from being overwritten (again).
> chore: update required checks

- .github/workflows/release.yaml
Attempting to fix the releasing action.
> chore: fix release action

- repositories.bzl
Update `repositories.bzl` with `go.mod` via `make update-bazel-repos`
> bazel: update Go deps from go.mod

- internal/gengapic/BUILD.bazel
- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/helpers.go
- internal/gengapic/lro.go
- internal/gengapic/paging.go
- internal/gengapic/stream.go
* move config parsing logic into generator init()
* simplify stub call generation
> chore: small gengapic refactor

- internal/gengapic/client_init_test.go
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/lro_client_init.want
Fixes three Go package options for mixin protos in tests
> gapic: fixes go test packages

- internal/gengapic/paging.go
> gapic: gen protobuf v2 import for iterator usage

- internal/gengapic/example.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/empty_example_grpc.want
- internal/gengapic/testdata/foo_example.want
- internal/gengapic/testdata/foo_example_rest.want
> chore: add pkg.go.dev link to request struct examples

- internal/gengapic/BUILD.bazel
- internal/gengapic/gengapic.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/testdata/rest_HttpBodyRPC.want
- test.sh
> fix(gengapic): regapic fix missing return statement

- .github/workflows/deps.yaml
Reverts googleapis/gapic-generator-go#1105
> Revert "chore(deps): update googleapis/code-suggester action to v4"

- internal/gengapic/lro.go
> fix(internal/gengapic): add workaround to a delete lro

- internal/gengapic/example_test.go
- internal/gengapic/snippets_test.go
- internal/testing/sample/sample.go
For https://github.com/googleapis/gapic-generator-go/issues/1512
> chore(internal/testing): add SnippetsDirectory

- .github/workflows/ci.yaml
- .github/workflows/deps.yaml
- internal/gengapic/client_init_test.go
- internal/gengapic/generator.go
- internal/gengapic/gengrpc.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/host_port_opt.want
- internal/gengapic/testdata/iam_override_opt.want
* Initial allowlist: `cloudkms.googleapis.com`, `secretmanager.googleapis.com`
> feat(gengapic): conditionally enable cloud.google.com/go/auth

- internal/gengapic/paging.go
- internal/gengapic/testdata/method_GetManyThingsOptional.want
Related: https://github.com/googleapis/gapic-generator-go/pull/1541
> fix: add missing cast for proto optionals

- internal/gencli/gencli.go
- internal/gencli/root_file.go
- internal/gencli/service_file_test.go
- internal/gencli/testdata/root_file.want
- internal/gencli/testdata/service_file.want
> chore(internal/gencli): replace use of github.com/golang/protobuf

- go.mod
- go.sum
- renovate.json
- showcase/go.mod
- showcase/go.sum
> chore(.github): force renovate to use 1.21

- internal/gengapic/doc_file.go
- internal/gengapic/example.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_alpha_emptyservice.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/doc_file_beta_emptyservice.want
- internal/gengapic/testdata/doc_file_deprecated_emptyservice.want
- internal/gengapic/testdata/doc_file_emptyservice.want
- Added a comment on how to download the library
- Removed redundant code in package docs
Internal bug: 372979301
> chore: simplify package docs and add import statement

- internal/gengapic/paging.go
- internal/gengapic/testdata/gen_iterators.want
> fix: make iterator link clickable

- internal/gengapic/genrest.go
- internal/gengapic/testdata/rest_ServerStreamRPC.want
> fix: remove name collision with server streaming RPC helper
