- gengapic/client_init.go
- gengapic/client_init_test.go
- gengapic/doc_file_test.go
- gengapic/example.go
- gengapic/example_test.go
- gengapic/gengapic.go
- gengapic/gengapic_test.go
- gengapic/imports.go
- gengapic/lro.go
- gengapic/paging.go
- gengapic/paging_test.go
- gengapic/stream.go
- internal/printer/printer.go
The delete code were moved into internal/ when bootstrapping samplegen.
No real changes, just renaming.
> use shared utility code

- cmd/gen-go-sample/inittree.go
- cmd/gen-go-sample/inittree_test.go
- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/test.bash
- cmd/gen-go-sample/testdata/sample.want
- internal/printer/printer.go
Only struct members and no validation for now.
> make simple init tree work

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
Proto annotation only configures the codes to retry on.
Just use something sensible as backoff parameter.
> gengaic: read retry code configuration

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/stream.go
- internal/gengapic/testdata/method_ClientThings.want
- internal/gengapic/testdata/method_ServerThings.want
None of the currently proto-annotated cloud APIs use server or client
streaming right now, so I haven't gotten a chance to baseline-test this
against production. Still, I believe problems (if any) will be small
and easily fixed in a followup, and we'll likely catch them when we
test with Showcase [1].
[1] Showcase is an API we created to exercise various functionalities
of the generator. It has an in-memory implementation we can test
against.
> generate streaming methods

- internal/gengapic/gengapic.go
Checks that `loc.LeadingComments` is not `nil` before dereferencing it.
I ran into this after I pulled master of this repo and tried to generate a client for the [Kiosk API](https://github.com/googleapis/kiosk/blob/master/protos/kiosk.proto).
I'm not entirely sure what a LeadingComment is. Also not sure if something about this proto made it crash or if it was something else I did. Once I put the check in, the plugin progressed passed the afflicted `init` method.
> fix panic from nil LeadingComments

- internal/gengapic/client_init.go
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/lro_client_init.want
Removes dependency on internal module with the same approach used in [gapic-generator#2390](https://github.com/googleapis/gapic-generator/pull/2390).
> inline go version reporting into the client

- internal/gencli/cmd_file.go
- internal/gencli/testdata/copy-todos.want
- internal/gencli/testdata/manage-todos.want
Per [discussion](https://github.com/googleapis/gapic-generator-go/pull/53#discussion_r238512569) in #53 , generated client streaming commands should ignore blank lines. They can be terminated with a `ctrl+D` sequence.
> gcli client stream ignore blanks

- internal/gencli/gencli.go
- internal/gencli/util.go
Detect nested types (for naming purposes) using `ParentElem` map to address brittleness pointed out [here](https://github.com/googleapis/gapic-generator-go/pull/53#discussion_r238442110)
Detect processing of `oneof` fields within an already nested message field (for naming purposes) using descriptor comparison (instead of name) prompted by [comment](https://github.com/googleapis/gapic-generator-go/pull/53#discussion_r238442447) on brittleness/confusion
> improve detection of nested types/msg fields

- README.md
Set release level to `beta`. Will be set to `release candidate` when work starts to get stakeholders involved in consumption & feedback.
> add release level badge to README

- Dockerfile
- Makefile
- README.md
- gapic.sh
* add `Dockerfile` for invocation wrapper image per micro-generator docker invocation spec
* add Makefile w/image building target
* add docker wrapper usage instructions to the README
* add copy of `gapic.sh` from [gapic-generator-python](https://github.com/googleapis/gapic-generator-python/blob/master/gapic.sh) w/added required flag
Note: Using `debian:stable-slim` as the base image because I couldn't get `alpine` to work (would always get `protoc: not found` even though it was in the right dir & marked executable). Image is only 65.6MB in size.
This was tested on linux & macOS machines.
Once this is merged, I will manually publish images tagged `0.1.0`  (only current release) & `latest`
> add docker invocation wrapper

- .circleci/config.yml
* add `publish_image` job & `build_test_publish` workflow to Circle CI config
Note: this was adapted from `gapic-generator-python`
> add image build & publish workflow to Circle CI

- .circleci/config.yml
Only trigger full workflow on tags that look like `v0.0.0` or `v0.0.0-something`
Note: CircleCI uses Java regexp and it [does not support conditionals](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html), so the regexp used here is a bit clumsy
> fix circleci publish trigger regexp

- .circleci/config.yml
For real this time...I swear...perms are more lax in the $GOPATH/bin I believe
> fix circleci gcr helper download path

- internal/gengapic/client_init.go
Mirroring work for [gapic-generator #2483](https://github.com/googleapis/gapic-generator/issues/2483)
Note: tested by successfully generating & installing a couple of gapics, and by running showcase tests, since the imports aren't covered in the diff testing
cc @jadekler
> change gapic gax-go to v2

- internal/gengapic/gengapic.go
- internal/gengapic/markdown.go
Takes initial step of changing the panic at unknown markdown types to a warning, described in #70 
While evaluating generated output for Go Cloud clients, missing `pkgName` in client example headers caused some automated vetting (a comparison to `goimport` output) to fail.
> change markdown panic to warning

- docker-entrypoint.sh
* warns about skipping unrecognized flags prefixed with `--go-gapic`
* skip all other unknown flags and values
> fix flag parsing in docker-entrypoint

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
Fix #74 
* group RPC retries based on idempotency
* add `ABORTED` and `UNKNOWN` to the existing idempotent retry config
* add retry config on `UNAVAILABLE` for non-idempotent methods
> add more default retry codes

- docker-entrypoint.sh
- gapic.sh
- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/doc_file.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/service_config.go
- internal/gengapic/testdata/doc_file.want
* adds `gapic-service-config` plugin option
* uses service config as **primary** source for the documentation summary header comment
* uses service config as **secondary** source (defers to annotations when present) for API Name, oauth scopes, and default_host 
This is a temporary workaround for: 
1. severely delayed metadata annotations
2. annotation config lacking the doc summary content
3. TBD acceptance of the oauth scope & default_host annotations
This workaround can be removed entirely once the above gaps have been closed. Also, individual workarounds can be removed as each individual gap is closed.
> add minimum service config support

- internal/gengapic/client_init.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
Per offline discussion, the `INTERNAL` status code will not be retried _at all_.
> remove retry internal status code

- .circleci/config.yml
I noticed that most of the go images in GCR start with a 'v'. Unless there's a reason for doing it that way, it may be better to just stick to the convention of using a version number.
> Strip 'v' from release tags

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/testdata/host_port_opt.want
Per offline discussions with @lukesneeringer and comparing to [gapic-generator-python](https://github.com/googleapis/gapic-generator-python/blob/master/gapic/templates/$namespace/$name_$version/$sub/services/$service/transports/base.py.j2#L42-L45), a port present in the `google.api.default_host` annotation value should be respected. A default of `443` should be used otherwise.
Note: This was not explicitly stated in the implementation or configuration specification documentation.
> respect default_host port if present

- README.md
* Add brief documentation of GAPIC configuration proto annotations to README (per this [tweet](https://twitter.com/JaimeGagoTech/status/1091528355432718337))
> add config annotation section to README

- internal/gengapic/example.go
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/foo_example.want
Fixes #107 
Fixes [google-cloud-go#1356](https://github.com/googleapis/google-cloud-go/issues/1356)
In generated example snippets, add comment beside request payloads indicating import path of struct and for the iterator type.
@broady @jadekler can you review?
> gengapic: add import comment in example snippets

- cmd/protoc-gen-go_cli/main.go
- cmd/protoc-gen-go_gapic/main.go
- internal/gengapic/gengapic.go
Per the `plugin.proto` [documentation](https://github.com/protocolbuffers/protobuf/blob/d9ccd0c0e6bbda9bf4476088eeb46b02d7dcd327/src/google/protobuf/compiler/plugin.proto#L99-L100), when code generation fails the plugin should *not* crash, but instead report the error via the `CodeGeneratorResponse` and `exit 0`. 
This PR implements that error reporting style in `protoc-gen-go_gapic` and `protoc-gen-go_cli`.
> plugins: report error in res rather than crash

- internal/gengapic/client_init.go
- internal/gengapic/gengapic.go
- internal/gengapic/lro.go
updates several error messages for config annotation error modes common among micro-generators per gapic-config-validator conformance utility (integration into CI coming once it is open-sourced)
> gengapic: update config-related error msgs

- .circleci/config.yml
- Dockerfile
- docker-entrypoint.sh
* adds the `gapic-validator` plugin to Docker wrapper's `protoc` invocation
* adds `gapic-error-conformance` step to CI
> chore: integrate config validator & error conformance testing

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/lro.go
- internal/gengapic/paging.go
- internal/gengapic/stream.go
- internal/gengapic/testdata/method_GetBigThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Fixes #114 
Adds insertion of request header params based on HTTP extension's pattern value
> gengapic: add http-based request header param support

- utils/showcase.bash
bumps gapic-showcase version to 0.0.16
> chore: update gapic-showcase to 0.0.16

- internal/gengapic/lro.go
* support use of nested message types (only 1 level deep) for LRO metadata & response types
* real use case in Ads `RunMutateJob` ([example](https://github.com/googleapis/googleapis/blob/adsgen/google/ads/googleads/v1/services/mutate_job_service.proto#L82) in `adsgen` branch)
* add TODO for eventually migrating from pbinfo to [protoreflect/desc](https://godoc.org/github.com/jhump/protoreflect/desc)
> gapic: support LRO types nested 1 level deep

- internal/gengapic/client_init.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/host_port_opt.want
It was decided that we cannot safely retry `UNAVAILABLE` by default for non-idempotent methods. This CL removes the generation of the default retry configuration for such methods.
> gapic: remove nonidempotent default retry

- internal/gengapic/lro.go
Improves nested LRO type name resolution using the `pbinfo.NameSpec` method. 
Should've done it this way to begin with...
> gapic: use NameSpec for nested lro types

- Makefile
- internal/gengapic/gengapic_test.go
- internal/gengapic/paging.go
- internal/gengapic/paging_test.go
- internal/gengapic/testdata/method_GetManyThings.want
- internal/pbinfo/pbinfo.go
Fix #123 
* add `Response *foopb.Foo` field to gen'd `FooIterator` type to preserve original response
* set `it.Response` to `resp` of fetch
* add `make golden` target for updating `want` files
> gapic: add Response to gen'd iterator type

- internal/gengapic/paging.go
- internal/gengapic/paging_test.go
- internal/gengapic/testdata/method_GetManyThings.want
I realized a little late that generated Iterator structs are "singletons" based on the **repeated field type**. There is only one iterator class generated for a `repeated Foo foo = 1;` field, `FooIterator`. Any RPC that implements the paging interface that pages over such a field will use the same `FooIterator` struct. However, the RPC responses might (most likely) differ. ListFoo and ListFooAgain might have ListFooResponse and ListFooAgainResponse response types, resulting in the recently added `Response {RPC response type pb}` field breaking.
An example exists today in the Cloud Vision API between the [ListProductsResponse](https://github.com/googleapis/googleapis/blob/152dabdfea620675c2db2f2a74878572324e8fd2/google/cloud/vision/v1/product_search_service.proto#L456-L463) and the …
> gapic: make iterator.Response an interface

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetBigThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
#114 did this incorrectly based on [aip/4222](https://aip.dev/client-libraries/4222). This PR fixes that.
* Multiple key-value pairs are concatenated with `&`
* The entire "query" is URL encoded (prevents stuff like https://github.com/googleapis/gax-nodejs/issues/520)
* Implements nested request parameter access
> gapic: fix header request params

- internal/gengapic/gengapic.go
- internal/gengapic/testdata/method_GetBigThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Encodes the keys & values of `x-goog-request-params` pairs separately.
Fixes #144
> gapic: encode metadata pairs separately

- internal/gengapic/client_init.go
- internal/gengapic/doc_file.go
- internal/gengapic/service_config.go
* remove use of API service config for:
* host
* oauth scopes
Both the `default_host` and `oauth_scopes` annotations are accepted. The `default_host` annotation is injected by proto publishing pipeline. The use of oauth_scopes from svc config will be confusing since we should have annotations and the svc config should only be used to capture documentation that only resides there.
> gapic: remove API service config scope support

- cmd/gen-go-sample/inittree.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/testdata/sample_empty.want
- cmd/gen-go-sample/testdata/sample_empty_object.want
- cmd/gen-go-sample/testdata/sample_lro.want
- cmd/gen-go-sample/testdata/sample_map_out.want
- cmd/gen-go-sample/testdata/sample_write_file.want
Similar to https://github.com/googleapis/gapic-generator/pull/2844 in gapic-generator.
> SampleGen: allow using `{}` to specify an empty object in request

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/paging.go
- internal/gengapic/paging_test.go
* adds a `generated` field to the `iterType` 
* makes the auxiliary types a generator field for tracking across services
* only generate an iterator once per **package**
Attempting to generate the Ads v2 GAPICs results in a iterator type naming collision.
> gapic: avoid generating duplicate iterators

- renovate.json
The `blackfriday` dep is an indirect dep of `github.com/golang-commonmark/markdown` and it actually moved to gitlab, from github. When updating the parent dep we will see if an update to `blackfriday` is necessary. But we shouldn't try to update it independently because the owner has kind of borked the import path as shown in #166
> chore: ignore blackfriday dep & have bot tidy

- go.mod
Remove indirect dependencies from go.mod because renovatebot is annoying.
> chore: prune indirect deps

- cmd/gen-go-sample/inittree.go
- cmd/gen-go-sample/main.go
- cmd/gen-go-sample/main_test.go
- cmd/gen-go-sample/testdata/sample_unary.want
- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
Generates function-level comments.
* a comment describing what the sample does. Generated from `description` field in sample config.
* comments describing what each parameter is. Generated from `request.comment` field in sample config.
Open questions:
* Not following GoDoc style?
* @jadekler mentioned in Chat that samples don't necessarily need to follow GoDoc styles.
* It's hard to implement because that will require either the generator to construct a grammar correct English sentence from user-specified sample config or enforcing some conventions to the `request.comment` field in sample config.
* Is it OK to use a `:` between the parameter name and the comment?
> SampleGen: Add function-level documentation

- docker-entrypoint.sh
I forgot to add the release level flag to the docker entrypoint
> gapic: add release-level flag to docker entrypoint

- .circleci/config.yml
Having `-mod=readonly` blocks the tests for PRs sometimes and it is annoying.
> chore: remove -mod=readonly in CI tests

- Dockerfile
- docker-entrypoint.sh
* change api-common-protos docker dep to `latest` tag to pick up `master` changes
* remove gapic-config-validator plugin from Docker image as it throws errors on things that are irrelevant to Go GAPICs
> chore: change docker dep on common-protos to latest

- .gitignore
- Makefile
- utils/showcase.bash
* updates SHOWCASE_VERSION to `v0.6.0`
* `utils/showcase.bash` downloads `showcase_grpc_service_config.json` for GAPIC generation
* add retry config to clean target & .gitignore
> chore: update showcase tests to v0.6.0

- internal/gensample/plugin.go
Without this check, the generation will fail with SIGSEGV.
Fix #248
> fix: better error message when 'go_gapic_opt' is not provided 

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetBigThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Nested field names for header request params were not being recognized by the parsing regex. This fixes the regex and updates the test.
> gapic: fix parsing nested request params

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetBigThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Some APIs have additional_bindings defined in their HTTP rules that reference a different request message field than the top-level rule. This PR collects all of the HTTP rules for an RPC and parses out the header request params.
> gapic: support additional_bindings in header params

- internal/gengapic/lro.go
The monolith generated `Wait` methods with an `error` return type when `google.protobuf.Empty` was the `response_type`. To avoid a breaking change, this adopts that approach.
@jadekler
> gapic: fix lro handling Empty

- internal/gengapic/example.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/lro.go
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/foo_example.want
- internal/gengapic/testdata/method_EmptyLRO.want
- internal/gengapic/testdata/method_RespLRO.want
#258 neglected to update the corresponding `return` statements based on the `response_type`. This fixes that.
It also neglected to fix the example files, which would fail to compile. This fixes that.
It also updates all of the relevant tests, adding more for the special cases.
> gapic: fix lro wait returns

- internal/gengapic/paging.go
- internal/gengapic/paging_test.go
* fixes auto-pagination criteria to allow multiple repeated fields if the first visited is the first repeated field by field number per aip.dev/4233
* fixes handling of nested message types in the auto-pagination logic
> gapic: fix paging criteria & nested message handling

- internal/gengapic/lro.go
- internal/gengapic/testdata/method_EmptyLRO.want
When the `gapic-generator` encountered an LRO response_type of google.protobuf.Empty, it would generate a very minimal implementation for `Wait` and `Poll`. Previously, the microgenerator aimed to keep the internals of these methods similar regardless of the LRO response_type. This produces some hard-to-read code. Rather than make it simpler in the generator, but harder to consume in the generated client, this PR takes the complexity into the generator and restores the monolith's simpler implementation for Empty LROs.
> gapic: simplify Empty LRO methods

- internal/gensample/gensample.go
- internal/gensample/gensample_sampleconfig_test.go
- internal/gensample/gensample_test.go
- internal/gensample/schema_v1p2/schema.go
- internal/gensample/schema_v1p2/schema_test.go
- internal/printer/printer.go
This ensures we do not generate standalone samples for a sample config that only requests in-code samples.
This adds utility functions to determine whether a sample config requests standalone samples or in-code samples (it can request both, of course).
Includes tests.
This fixes #244.
> Support sample_type field in sample config.

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/pbinfo/pbinfo.go
Currently, `camelToSnake` will split a name like `IAMCredentials` into `i_a_m_credentials` which is incorrect. With this change `camelToSnake` respects upper case acronyms in conversion.
Furthermore, a special case is added during proto service name reduction for `IAM` APIs in order to avoid a breaking change. 
Fixes #282
> gapic: fix acronym handling in camelToSnake

- internal/gengapic/client_init.go
- internal/gengapic/example.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/pbinfo/pbinfo.go
RPCs for the `google.longrunning`package shouldn't be generated with the LRO helpers because they are ordinary RPCs. This makes inference of LRO-help generation ignore the `google.longrunning` package.
This also adds tracking of the method-to-parent file mapping to `pbinfo`.
> gapic: fix LRO handling for longrunning pkg

- WORKSPACE
- internal/gengapic/BUILD.bazel
- internal/gengapic/client_init.go
Go uses the American-English spelling `CANCELED`, while the gRPC code name uses the British-English spelling `CANCELLED`.
> gapic: fix spelling of canceled

- internal/gengapic/client_init.go
Fixes #316 by moving the retry-related import inclusion into the condition where we are generating a populated retry config. It is added to a loop so the generated import map could be accessed a lot, but it's preferred to nesting the code in another conditional check or a separate loop.
> gapic: fix naive retry related imports

- internal/gencli/flag.go
This sets the default flag value for instances of the `page_size` field to `10` instead of `0`. It also prepends the default to the flag usage documentation.
I tested this with [gapic-showcase](https://github.com/googleapis/gapic-showcase).
Fixes #315 
cc: @odsod
> gencli: set default for page_size to 10

- internal/gencli/cmd_file.go
Adds support for `repeated` fields using an `enum` type.
Fixes #319 
cc: @ericwenn @odsod
> gencli: support repeated enums

- rules_go_gapic/go_gapic_pkg.bzl
This macro was originally implemented in [gapic-generator](https://github.com/googleapis/gapic-generator/blob/15ec21be63aac27b8f02d5e1d3816b48c83d9fbe/rules_gapic/go/go_gapic_pkg.bzl). This is a direct copy of that to consolidate Go client generation support for the Bazel interface.
> bazel: copy go_gapic_assembly_pkg macro impl

- internal/gencli/gencli.go
This moves the check for enum fields while constructing flags to _after_ the check for `field_behavior` being `OUTPUT_ONLY`. The presence of an enum flag normally results in `strings` being imported for string-to-value conversion. If the enum field is `OUTPUT_ONLY`, then a flag is never made for it, but the `strings` import persists, resulting in an unused import.
Fixes #333 
@ericwenn
> gencli: ignore output_only enums

- internal/gencli/root_file.go
- internal/gencli/testdata/root_file.want
This means outputs can also be used as inputs via the --from_file flag.
Fixes #336.
> Use jsonpb to marshal json message output

- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
I needed to tighten the regexp added in #341. It was capturing too much, incorrectly.
> gapic: tighten reference link parser regexp

- Makefile
- internal/gencli/cmd_file.go
- internal/gencli/flag.go
- internal/gencli/gencli.go
Fixes variable name generation for `enum` fields belonging to a nested `oneof`: the `enum` field's name was being stripped incorrectly. 
Fixes variable name referencing in flag generation for nested messages that belong to nested messages that are a `oneof` field: the name of the nested messages following that of the nested message `oneof` field shouldn't be included.
Fixes pagination detection, requiring both `page_size` and `page_token` request message fields in stead of just one or the other (naively). 
Fixes a missing `fmt` import when there is `oneof`, which is used for `fmt.Errorf` in the `default` case of the `switch` that sets the `oneof` field based on the selector value.
Fixes #344 
Also disables the integration testing script for protoc-gen-go_cli in the `test-go-cli` Make …
> gencli: fix handling deeply nested msg in oneof

- internal/gengapic/gengapic.go
After exploring consolidation of the `emptyType` and `emptyValue` constants, I think consolidating them doesn't make sense. They influence different code paths and the `.` prefix on `emptyType` has semantic meaning (it indicates protoc resolved it as a fully qualified name). It would be more confusing & brittle, imo, to write prefix stripping or addition code in multiple places if we got rid of one of them. Thus, I changed the `emptyType` to instead prefix the `emptyValue` directly.
Fixes #260 
Note: the `.` prefix business might be different if we move the plugin implementation to the protobuf v2 plugin API (just a guess, haven't looked at it).
> chore: refactor Empty type constants

- util/cmd/release/main.go
Creating `v0.13.0` was the first release with automated release notes. It worked great except for the extraneous single quotes I wrapped the generated notes in thinking it was necessary to escape the generated text block in the `exec`'d command. The single quotes actually just ended up in the release notes, making the leading header malformed (`'# gapic`), and trailing the last commit message.
> chore: remove extraneous quotes on release notes

- internal/gencli/cmd_file.go
- internal/gencli/root_file.go
- internal/gencli/testdata/root_file.want
Paged responses does not implemented `proto.Message` and the output was not JSON encoded.
> gencli: JSON output of paged responsed

- rules_go_gapic/go_gapic_pkg.bzl
Today, `go_gapic_assembly_pkg` produces an invalid archive. The proper files are in the archive, but the file paths are prefixed with `../`. This makes extraction fail. 
Also, the `chmod` for the GAPIC code fails because it attempts to use the raw importpath, which includes a trailing `;package`. There isn't such a directory, so this strips that suffix, resulting in the proper directory being targeted.
> bazel: fix assembly_pkg archive contents path

- repositories.bzl
- rules_go_gapic/go_gapic_repositories.bzl
Changes to Bazel respositories:
* updates go-genproto commit hash used in the generator (matches `go.mod`)
* updates the `google.golang.org/api` version used to compile the generated client libraries (matches `google-cloud-go` `go.mod`)
Note: tested locally against googleapis/googleapis
> bazel: update repositories with latest

- cmd/protoc-gen-go_cli/main.go
- cmd/protoc-gen-go_gapic/main.go
This changes the use of `Unmarshal` from the `CodeGeneratorRequest` to the general `proto.Unmarshal`. The former is removed in golang/protobuf v1.4.0 and it is breaking builds that are pulling this tool and latest golang/protobuf.
> chore: change plugin use of Unmarshal

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Updates the header request param parsing regex to include those path variables that do not have a trailing segment delimited by a '='.
`"/v2/{parent=projects/*}/locations/{location_id}/content:inspect"` now results in both `parent` and `location_id` being included in `x-goog-request-params` rather than just `parent`.
> gapic: fix header request param parsing

- renovate.json
Instructs renovatebot to rebase when the branch is behind
Changes `assignees` to `reviewers`
Adds label `automerge` on PR creation
> chore: renovatebot rebase when behind

- Makefile
- cmd/protoc-gen-go_cli/main.go
- cmd/protoc-gen-go_cli/test.sh
- internal/gencli/cmd_file.go
- internal/gencli/cmd_file_test.go
- internal/gencli/flag.go
- internal/gencli/gencli.go
- internal/gencli/testdata/create-todo.want
Adds support for proto3_optional to the `go_cli` plugin. Fixes #378 
* Primitives and enums are supported, while optional messages aren't generated differently by protoc-gen-go.
* Adds a diff test for each case
* Simplifies `go_cli` integration testing script - strips it down to just a gapic-showcase gen/build test (Fixes #345)
* replaces `go_cli` testing script in `test-go-cli` Makefile target
> gencli: proto3_optional support

- internal/gencli/gencli.go
A field marked with `optional` also gets a `oneof` selector with the same name preceded by a `_`. This ensures this doesn't get generated as a oneof would, because they are handled differently by go_cli
> gencli: fix handling proto3_optional oneof

- WORKSPACE
- repositories.bzl
Update rules_go v0.23.0 and gazelle v0.21.0
Update indirect dependency on com_google_cloud_go to latest release v0.57.0 (in relation to #387)
> bazel: update rules_go v0.23.0 and gazelle v0.21.0

- .circleci/config.yml
- WORKSPACE
* Updates CI `protoc` version to stable `v3.12.0`, removing TODO for this
* Removes TODO comment to update `WORKSPACE` version of `protoc` to stable `v3.12.0` (update actually done by renovatebot previously)
> chore: update CI to protoc stable v3.12.0

- internal/gencli/cmd_file.go
- internal/gencli/flag.go
- internal/gencli/gencli.go
- internal/gencli/util.go
Addresses part of #368 
Tested with showcase and the afflicted secretmanager api
> gencli: fix oneof naming collision

- internal/gencli/cmd_file.go
- internal/gencli/flag.go
- internal/gencli/gencli.go
Support `map<string, string>` fields because it is often used for `labels` in `googleapis`. Explicitly choosing not to support other `map` types for now, until a need presents itself. 
This is kind of a workaround in that it piggy-backs on the `repeated Message` code, while suppressing the unmarshal part in place of a `key=value` string split and assignment. If other types are to be added, this will need to be redone.
Fixes #368
>  gencli: support map<string,string> fields

- repositories.bzl
- rules_go_gapic/go_gapic.bzl
- rules_go_gapic/go_gapic_repositories.bzl
`go_gapic_library` compiles the generated package via `go_library` and uses a trimmed `importpath` that excludes the trailing package alias `;alias` component. This allows `go_gapic_library` targets to shade  dependencies on `com_google_cloud_go`. In particular, this allows `//google/longrunning:go_gapic` to overwrite the `@com_google_cloud_go//longrunning/autogen` dependency used by many `go_gapic_library` targets. To make this work, we need to exclude a manual file in the `longrunning/autogen` package. The code in the manual file is not used in any of the GAPIC's, so it is not an issue during compilation. 
This also adds `com_google_cloud_go` to the `go_gapic_repositories.bzl` macro instead of having it pulled in by a weak dependency in the `gapic-generator-go` `repositories.bzl`.
This …
> bazel: fix go_library importpath & lro shading

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/paging.go
- internal/gengapic/testdata/method_GetManyThingsOptional.want
It is not recommended, but possible that an API produce will use the `proto3_optional` label on `page_size` or `page_token`. The generated Iterator implementation referenced these fields on the request message directly in spots. If `proto3_optional`, these primitive types become pointers and the generated code would break.
This updates that code to be aware of `proto3_optional` in assignments (i.e. use the `proto.{Type}` wrapper) and it changes direct accesses to getters (i.e. `req.GetPageSize()` rather than `req.PageSize`).
Note: the Iterator design does not account for `proto3_optional` `page_size` and `page_token` fields and by switching to getters (which return the type's default value i.e. `0` for `int32` when unset), the Iterator effectively renders the effect of `proto3_optional` …
> gapic: support proto3_optional in paging helper

- internal/gengapic/doc_file.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
Updates the generated `doc.go` package documentation to reference pkg.go.dev/cloud.google.com/go rather than godoc.org.
> gapic: fix godoc link in pkg docs

- repositories.bzl
Updated the Go deps in `repositories.bzl` via the `go.mod` and `gapic-generator` to the latest release (which contains Bazel helpers used for this generator's Bazel rule implementation).
> chore: update bazel repos with go.mod

- internal/gengapic/gengapic.go
This fixes a bug where the `time` stdlib is not being imported but necessary for the default deadline logic. It was not caught before because `time` was imported by other parts of the client (retry, lro, etc.).
> fix: include time import with deadline

- README.md
- internal/gengapic/gengapic.go
Adds a generator option to strip the given module prefix from the `go-gapic-package` value when used in the generated filenames. Similar to the [protoc-gen-go option](https://go-review.googlesource.com/c/protobuf/+/219298/). So, if the plugin output directory is the module root, the generated code will directly overwrite the existing files.
Fixes #447
> gapic: add module generator option

- CONTRIBUTING.md
- Makefile
- WORKSPACE
- go.sum
- repositories.bzl
This wraps the `gazelle` `update-repos` command in Make target to simplify updating the Bazel repositories with the Go modules.
`gazelle` will only generate `go_repository` rules to load Go module dependencies, but we like to wrap our dependencies with a `_maybe` macro, in case another section earlier in a WORKSPACE has already imported the dependency. So, I've defined a `go_repository` macro that invokes `gazelle`'s `go_repository` with our `_maybe`. `gazelle` `update-repos` continues to generate `go_repository` rules from our `go.mod`. 
We also have to do a little find-remove because `gazelle` generates a load statement for `go_repository` even though we have already loaded it with an alias (`gazelle_go_repository = "go_repository"`).
Finally, the last hack, the `go.sum` declares …
> chore: wrap gazelle update-repo in make

- rules_go_gapic/go_gapic.bzl
Recent changes to plugin param parsing made sending an empty `release-level` param an error. The bazel macro defaults the `release_level` attribute to `""` and was supplying `"release-level="` if it went unset, which would produce an error even though this attribute/param is optional. There is no bug in googleapis today as the param parsing changes haven't been released, but updating this generator in the WORKSPACE would've caused the error to happen.
Tested this fix against all of googleapis.
> bazel: fix empty release-level param

- rules_go_gapic/go_gapic.bzl
Use the rules_go WKT for some common types instead of directly depending on the Go module that owns them for deps included by the generator on behalf of the generated client.
Cleans up some import conflict warnings.
> bazel: use WKT for extra gapic deps

- .github/CODEOWNERS
Expand the CODEOWNERS from just `yoshi-go` to include `actools-go`.
> chore: expand codeowners add actools-go

- rules_go_gapic/go_gapic_repositories.bzl
Updates the Go deps needed by a Go GAPIC to compile when built with Bazel. These deps are provided by the generator, but are not necessary for the _generator_ to compile.
These were pulled from https://github.com/googleapis/google-cloud-go/blob/master/go.sum.
Tested locally against the googleapis WORKSPACE.
> bazel: update generated Go gapic deps

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/host_port_opt.want
The option "WithEndpoint" is intended for user override only, and specifying it will interfere with mTLS endpoint selection. See details regarding mTLS at https://google.aip.dev/auth/4114
> gapic: use DefaultEndpoint and DefaultMTLSEndpoint for default options

- WORKSPACE
Updates the `rules_go` bazel dep to `v0.25.1` and adds the newly required `version` label for the Go SDK version used in `go_register_toolchains`. I picked Go 1.13.15 (the latest Go 1.13.x version to date) because the `go.mod` names 1.13 as the desired version.
This should allow us to merge #480 as there was a fix for Well-known types (WKT) in rules_go v0.25.x.
> bazel: update rules_go with version label

- internal/gengapic/paging.go
- internal/gengapic/paging_test.go
- internal/gensample/paging.go
Previously, if an RPC had all of the necessary Pagination fields according to AIP-4233, but was missing a repeated field, the generator would fail. This is not a requirement of AIP-4233, instead it should treat the RPC as if it wasn't paginated, and generate a standard method.
Fixes #493
> fix: relax paging missing repeated

- go.sum
Go tool reported that the `go.sum` is out-of-sync with the `go.mod`. `go mod tidy` fixes it.
> chore: fix out of sync go.sum

- .circleci/config.yml
- .github/workflows/ci.yaml
Adds a GitHub Actions config for running basic linting, unit tests and bazel testing.
To remove circleci we'd need to port: 
- Showcase integration tests
- Docker image creation + publication
- release script execution (this should probably be ported to release-please)
Once Actions is confirmed to work, I will remove the duplicate jobs from the CircleCI config if possible
cc @alexander-fenster: thanks for the example to work from. I copied some of Luke's configs from the api-linter (a Go project) for basic testing/linting.
> chore: run basic tests on Actions

- .circleci/config.yml
- .github/workflows/ci.yaml
- Makefile
- test.sh
This PR includes the following:
- moves Showcase testing into Actions
- moves googleapis generation smoke test into Actions
- adds googleapis generation smoke test to `make test` target
- removes now obsolete `build` job from CircleCi
Remaining CircleCi jobs are:
- docker image building
- release publication
- format check
Note: I'm not doing anything fancy with Actions here, I just tried to port the existing CI scripts/commands to Actions to get off of CircleCI. We can come back around and make things "idiomatic" later.
> chore: port integration tests to Actions

- .circleci/config.yml
- .github/workflows/release.yaml
This moves the GitHub release script from CircleCI to Actions.
> chore: port GitHub release to Actions

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
Addresses first part of #514 - capturing numbers in field names defined in `google.api.http` patterns for use in building the field accessor.
> fix: include numbers in header name regexp

- rules_go_gapic/go_gapic.bzl
The generator bazel rule needs to provide the protobuf-go v2 common type imports because protobuf changed the `go_package` of the protos to point at protobuf-go v2. See https://github.com/bazelbuild/rules_go/issues/2721
We can't upgrade the version of protobuf in googleapis because of that change.
> bazel: use protobuf-go v2 common types

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetManyThingsOptional.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
This adds support for non-`string` field types that are declared as header request params. For non-`string` types, the value at runtime is not `url.QueryEscape`'d. For proto field types that translate to a `float64`, the `%g` formatter is used to format the value in either exponent or decimal form depending on what is best. See https://golang.org/pkg/fmt/ for more on format modes. The resulting formatted value is `QueryEscape`'d in case there is a `+` in the exponent section.
A helper `lookupFieldType` in order to learn the type of the field declared as a header request param.
Furthermore, the existing tests were updated to account for the new lookup of field types in header request param construction. New tests were also added to cover the new methods.
Open TODO to handle `[]byte`.
#514
> fix: handle non-string header field types

- internal/gencli/gencli.go
- internal/pbinfo/pbinfo.go
Protobuf 3.14 changed the `go_package` of the well known types to reference those in the protobuf-go v2 project. The package names have a `pb` suffix already and our code was appending `pb` again. This stutter is a little annoying so let's not do it!
This change is also applied to the `gencli` pkg where some of the pbinfo code is copied for specific usage.
> gapic: conditionally append pb to import alias

- README.md
- WORKSPACE
- internal/gengapic/BUILD.bazel
- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/metadata.go
- internal/gengapic/metadata_test.go
- internal/gengapic/options.go
- internal/gengapic/options_test.go
- repositories.bzl
- rules_go_gapic/go_gapic.bzl
Adds generation of  the `gapic_metadata.json` file containing the proto-to-client mapping of the generated code.
The schema for GAPIC Metadata is defined in [googleapis](https://github.com/googleapis/googleapis/blob/master/gapic/metadata/gapic_metadata.proto).
Enable generation via the plugin option `metadata`. See README for more info.
Note: I needed to override the `go-genproto` dependency because `rules_go` brings an older version that is missing the `GapicMetadata` proto. See #529.
> gapic: add gapic_metadata.json generation

- rules_go_gapic/go_gapic.bzl
Don't attempt to unzip the metadata srcjar if metadata generation was disabled as the archive will be empty and produce an error.
> bazel: ignore metadata.srcjar if disabled

- internal/gengapic/metadata.go
- internal/gengapic/metadata_test.go
Sometimes, when the `package` name matches the reduced service name (the proto Service name sans `"Service"` suffix), the generated client type is named `Client` as the `servName` variable is `""`.
This accounts for that with the metadata generation.
> gapic: fix empty libraryClient in metadata

- internal/gengapic/metadata.go
- internal/gengapic/metadata_test.go
The `Client` suffix of the generated client's type is hardcoded everywhere in the generator's printing logic. We need to append it any entry we are given, including `""`.
> gapic: fix metadata libraryClient naming

- internal/gencli/cmd_file.go
When a message contains a `map<string,string>` field, the generated CLI allows map values to be set by accepting multiple options of the form:
```--parent.mapname "key=value"```
However, when these options are provided, the CLI crashes because the generated CLI attempts to store them in a map that hasn't been created yet. The map insertions crash because the map field is nil.
This commit adds code that creates maps if one or more of the options illustrated above is provided. With these maps, the associated API calls are made successfully.
> gcli: fix a crash in generated CLIs.

- internal/gencli/flag.go
- internal/gencli/gencli.go
- internal/gencli/util.go
Properly handles oneof fields with a message type not defined in the same proto package when generating the oneof field wrapper type reference.
Add a reference to the`OneofDesc` that owns the `oneof` field flag to `Flag`. 
Refactors `getImport` off of the `gcli` type so it can be used in a "static" context.
Tested on gapic-showcase, the secrets API the issue was found on, and a couple other APIs.
Fixes #536
> gcli: fix oneof msg field in diff pkg

- .github/workflows/ci.yaml
- .gitignore
- internal/errors/errors.go
- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
- internal/gengapic/paging_test.go
- internal/pbinfo/pbinfo.go
- internal/pbinfo/prim2go.go
- internal/printer/printer.go
* clean up linter warnings in codebase
* add `go fmt` `golint` and `go vet` steps to the `lint` job
* upload linter reports in CI
* gitignore linter reports
> chore: clean up linter warnings

- .gitignore
- Makefile
- showcase/showcase.bash
This updates the version of `gapic-showcase` used in the integration tests.
It also adds download of the newly added Service config YAML file, and includes it in generation, the `.gitignore`, and the `make clean` target.
> chore: update showcase testing version

- .gitignore
- Makefile
- showcase/showcase.bash
Ignore VS Code Workspace files and also add `-mod=mod` to some test targets that failed due to some on-the-fly go.mod/go.sum changes.
> chore: ignore vs code workspace files

- WORKSPACE
- repositories.bzl
Fixes #529. Also updates `repositories.bzl` with `go.mod`.
> bazel: update rules_go, remove go-genproto override

- internal/gengapic/options.go
- internal/gengapic/options_test.go
Sometimes, a caller of the plugin will provide an empty plugin option flag `--go_gapic_opt=` which ends up in the comma-separated value `parameter` like `foo=foo,,bar=bar` and the option parser would report an invalid flag. They should just be ignored instead, which makes it easier on wrapper scripts, etc.
Fixes #558 
cc: @mscno
> gapic: ignore empty plugin flags

- .github/workflows/release.yaml
I neglected to port the docker image publishing from CircleCI, intentionally, as Bazel is the preferred option. But until we rescind https://aip.dev/4290, we need to be publishing an image.
This was mostly copied from `gapic-showcase` CI.
To help #558, a new image needs to be published.
> chore: build push image to gcr on release

- internal/gengapic/doc_file.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
The godoc link was fixed in #412 but it was still missing `https://` which means godoc doesn't render it as a hyperlink.
Fixes #563
> gapic: fix link in ctx docs

- internal/gengapic/doc_file.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
Some APIs include markdown in their API Service config documentation summary section - the field that is used as the Go package documentation. It should be parsed for markdown just like the proto RPC comments.
Fixes #562
> gapic: parse markdown in pkg doc string

- .github/workflows/deps.yaml
Adds a new workflow to automate updates to the `go_repository` targets in `repositories.bzl` that represent the Go deps for the project. 
When a commit lands on `master` that was created by `renovate-bot`, this workflow runs. It invokes the `update-bazel-deps` Make target that I've been doing manually. If there are changes to `repositories.bzl`, the changes are sent as a PR via `code-suggester`.
> chore: automate bazel Go dep updates

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/example_test.go
- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/mixins.go
- internal/gengapic/mixins_test.go
The main change in this PR is the use of the `http.rules` section to determine which mixin RPCs should be generated. Only those with such a binding will be generated. This is primarily because not every service implements all of the RPCs for a given mixin. The `http.rules` are the best indicator of this. Furthermore, those methods to generate will be overwritten with the `google.api.http` binding defined in the corresponding `http.rules` item. This way, the hosting service's http bindings are used for REGAPIC and header injection. 
This change also references the Service config's `documentation.rules` for method-level docs for the mixins. Absent those, a generic comment is added. 
Some refactoring of the mixin code is also done, in order to keep mixin logic inside of `mixins.go` and …
> gapic: gen mixins based on http rules

- Makefile
- go.mod
- go.sum
- showcase/go.mod
- showcase/go.sum
- showcase/showcase.bash
Updates Go deps (because renovate has been broken) and the Showcase version used for integration testing. 
It also attempts to fix the `update-bazel-repos` Makefile target, because it failed on the last dep update change.
> chore: udpate dependencies & showcase version

- .github/workflows/ci.yaml
- Makefile
- internal/gengapic/client_init.go
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/lro_client_init.want
- showcase/go.mod
- showcase/showcase.bash
The integration test script/job were silently failing. Once these were fixed, changes were needed to fix the new wrapper methods and get the tests to pass, including:
- expanding the `[]gax.CallOption` slice from `opts ...gax.CallOption` via `opts...`
- fix use of missing var in client-streaming RPC wrapper
- implement wrappers for `Close`, `setGoogleClientInfo` and `Connection`
> gapic: fix wrappers, add missing wrappers, fix CI

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/lro_client_init.want
This adds the missing LRO type wrappers and it also fixes the the client_init tests to produce accurate generated code (e.g. `ListLocations` should return  a `LocationIterator` nor a `ListLocationsResponse`.
> gapic: fix missing LRO type wrapper

- .github/workflows/ci.yaml
- internal/gengapic/client_init_test.go
- internal/gengapic/genrest.go
- internal/gengapic/options.go
- internal/gengapic/options_test.go
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- showcase/showcase.bash
- test.sh
This change generates code for unary and empty unary methods for REST
based clients.
TODO:
* Set http headers
* Handle query parameters
* Expose REST client factory function
* Add nil returning stubs for unsupported methods
> feat: generate rest client method implementation

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/gengrpc.go
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/lro_client_init.want
Since the wrapper methods are the "public facing" methods of a `Client`, we should generate the RPC documentation on them instead of the internal, transport-based, interface implementation.
> gapic: gen RPC docs on wrapper methods

- showcase/README.md
- showcase/compliance_test.go
- showcase/go.mod
- showcase/main_test.go
- showcase/showcase.bash
This tests the Showcase compliance suite against a running Showcase server. The client-side checks are merely that the returned data equals the sent data. However, when the requests are made over REST, the Showcase server will check various aspects of the REST transcoding, including optional field presence, headers, etc., and informatively fail the call if any of the checks fail.
**NOTE**: At the moment gapic-generator-go does not yet expose a factory function for REST clients. Using that when available remains a TODO. For the time being, we're using a gRPC client, which will trivially pass the test.
> feat: Integration test:  Showcase compliance suite

- go.mod
- go.sum
Forcing update of go-genproto in order to trigger Bazel dep mgmt action.
> chore: update go-genproto

- internal/gengapic/example.go
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/foo_example.want
IDK why the original implementation of example import hints only generated the hint for methods with non-Empty response types...but that doesn't seem right because a Delete still has to provide a request message, which always comes from go-genproto. Fixing that oddity and some weird conditional organization.
> gapic: include import hint in all examples

- internal/gengapic/genrest.go
The initial scope for DIREGAPIC is unary method calls, but clients
must still expose _all_ API methods in order to fit the internal interface.
Just return helfpul errors for now.
> feat: stub out currently unsupported method types for REST clients

- .github/auto-label.yaml
- .github/label-sync.yaml
- .github/product-label.yaml
I don't think the `product-label.yaml` file does anything.
> chore: fix config to ignore product labels

- internal/gengapic/gengrpc.go
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/lro_client_init.want
One issue we have seen pop up multiple times is around users of our
libraries not closing their clients after they are done being used.
This can lead to memory leaks as the underlying HTTP connections
are never closed. Adding some docs on the function that returns the
Client seems like a good first step to take.
> gapic: add docs on NewClient about closing the client

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetManyThingsOptional.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
Add support for Enum field types parsed from `google.api.http` path params to be used in request header parameters. 
Refactor `lookupFieldType` to `lookupField`.
Tested locally with an unpublished API that raised the issue.
Fixes #639
> gapic: support Enum fields in x-goog-request-params

- showcase/echo_test.go
- showcase/go.mod
- showcase/go.sum
- showcase/identity_test.go
- showcase/sequence_test.go
Simply switches use of protobuf-Go v1 with the v2 module in the `showcase` integration testing submodule.
> chore: refactor protobuf Go use in testing module

- internal/gengapic/genrest.go
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
GAPICs that build REST clients now include factory functions that
create REST clients, as well as commensurate utilities.
> feat: headers, utils, and REST client construction

- internal/gengapic/client_init_test.go
- internal/gengapic/gengrpc.go
This ensures that even if there are no API-specific request/response messages used in a Service's RPCs, that the generated protobuf Go pkg is still imported to fulfill the grpc client stub import.
Adds a test for the imports the generator must have after client init generation, an example of #435
> gapic: ensure API pb import is included

- internal/gengapic/gengapic.go
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetManyThingsOptional.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
- showcase/showcase.bash
Go protobuf code for enums makes them typed `int32` so in order to access the string representation of the enum, which is mapped with `int32` to `string`, we need to convert the enum value to an `int32` in the map key. 
This wasn't caught before, because the showcase proto with an enum http param wasn't being generated in the integration tests. It is added here.
> gapic: fix enum header conversion

- internal/gencli/gencli.go
Fixes an issue where the early continue caused the subcommand file to
not be written, and the remaining required imports to be omitted.
> gcli: fix paginated methods with primitive result types

- repositories.bzl
- rules_go_gapic/go_gapic.bzl
- rules_go_gapic/go_gapic_pkg.bzl
This is needed for the preliminary removal of the monolith rules from googleapis' `switched_rules_by_language`.
> fix(bazel): Remove monolith Bazel rule deps [go]

- showcase/compliance_test.go
This adds a `wipMethod()` stub to `compliance_test.go` to avoid failing on
methods that use features known to not yet be implemented in this
generator. This way the Showcase tests can be made part of CI even
while we continue to implement functionality.
Eventually, this stub should be removed when all the functionality is in place.
> chore: avoid failures on expected not-yet implemented features

- internal/gengapic/example.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/empty_example_grpc.want
- internal/gengapic/testdata/foo_example_rest.want
When `rest` only transport is targeted for generation, the generated example files do not adjust to use the `rest` client factory method instead of the gRPC one resulting in a compilation error when the _examples_ are compiled.
> gapic: fix example use of factory methods for REST transport

- internal/gengapic/metadata.go
- internal/gengapic/metadata_test.go
- internal/gengapic/testdata/metadata.want
protojson produces non-deterministic output in the form of adding
random amounts of space after keys. This causes unneeded diffs in
google-cloud-go. This is a hack to make the output deterministic.
More context: https://go-review.googlesource.com/c/protobuf/+/151340
Fixes: #691
> fix(gengapic): standardize output of metadata files

- internal/gengapic/genrest.go
Including `EmitUnpopulated` in the proto-to-json encoding results in unset fields being set with empty values, defeating the purpose of using `proto3` `optional` for field presence. A backend may interpret this as an error and return a `BadRequest` response.
> gapic: REST - remove EmitUnpopulated encoding option

- .github/workflows/ci.yaml
Apparently there is bugged code in an example application in googleapis: https://github.com/googleapis/gapic-generator-go/pull/703/checks?check_run_id=3049979631.
This moves the local download of googleapis to a separate directory so as to avoid being compiled via `go test ./...`
> chore: mv integration test protos to tmp

- rules_go_gapic/go_gapic.bzl
Adds `diregapic` flag added in #722 to the `go_gapic_library` macro.
> bazel: add diregapic flag

- internal/gengapic/genrest.go
- internal/gengapic/paging.go
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetManyThingsOptional.want
1) Only set page_token if it is not empty
2) Only set page_size or max_results if nonzero
3) Do not make a json request if the rpc has no body
> fix: rest pagination fixes

- internal/gengapic/doc_file.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/example.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
Fixes #591 
Adding sample client and method to the top of the docfile to make the entry point for using a package more visible to end users.
Example image of sample client + method for the Language API in attached image:
> gapic:  include example in package doc overview

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/testdata/rest_CustomOp.want
This excludes `GET` requests from custom operation wrapping in DIREGAPIC mode because those are always polling methods that should return the raw type. 
This will be a breaking change in the compute client for those few `GET` `Operation` methods, switching _back_ to the raw `computepb.Operation` as the return type.
It also includes a missing Go dep to generated regapic pagination.
> gapic: exclude GET from custom op wrapping

- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest.go
- internal/gengapic/helpers.go
- internal/gengapic/helpers_test.go
- internal/gengapic/paging.go
When a proto field has a number in a snake_case field name like `foo_123_bar`, protobuf-go generates the field name and resulting accessor as `Foo_123Bar` and `GetFoo_123Bar` respectively. We recently had an API add such a field, seemingly a first for us.
This change updates the `snakeToCamel` helper to account for that, and updates several places where it was being used directly to generate accessors to instead use the `fieldGetter` helper that uses `snakeToCamel` under the hood.
Fixes b/197160410.
> gapic: fix fields with nums

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
This excludes the `Wait` RPCs in DIREGAPIC APIs from having their return type be the custom operation wrapper. Instead, `Wait` RPCs will return the raw operation type. 
Note: This will be a breaking change for compute, but it is intended.
> gapic: exclude diregapic Wait RPC from op wrapping

- internal/gengapic/custom_operation.go
- internal/gengapic/gengapic.go
- internal/gengapic/genrest.go
I missed updating another spot where the custom operation decision logic was used, so I moved it into a function and used it in both spots.
> gapic: fix compute wait wrapping logic

- .github/workflows/ci.yaml
- internal/gengapic/doc_file.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/genrest.go
- internal/gengapic/helpers.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/rest_CustomOp.want
This adds generation and use of a `maybeUnknownEnum` helper to REST clients. This helper will `Wrap` proto-JSON parsing errors caused by the server replying with an unknown enum value. The goal is to produce a more friendly/actionable error message. See http://go/actools-regapic-unknown-enum for more details. The wrapped error produces an error message like the following:
received an unknown enum value; a later version of the library may support it: proto: (line 1:17): invalid value for enum type: "NOT_VALID_ENUM"
This is (hopefully) a temporary solution, with the long-term solution being a fix to the proto-JSON parsers. 
A companion PR for `compute` is at https://github.com/googleapis/google-cloud-go/pull/4710.
Note: This change introduces the `golang.org/x/xerrors` module as a …
> gapic: rest GAPIC wrap unknown enum error

- internal/gengapic/gengapic.go
- internal/gengapic/mixins.go
- internal/gengapic/mixins_test.go
We need to exclude the mixin proto files when they are present in the input from client generation, so that we do not generate extra clients.
> gapic: ignore mixin proto files in input when generating mixins

- internal/gengapic/gengrpc.go
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/host_port_opt.want
- internal/gengapic/testdata/iam_override_opt.want
Since https://github.com/googleapis/google-api-go-client/pull/1260 we need to start allowing the service config to be pulled.
cc @mohanli-ml
> gapic: remove disable serv config dial opt

- internal/gengapic/doc_file.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/rest_CustomOp.want
- internal/gengapic/testdata/rest_EmptyRPC.want
- internal/gengapic/testdata/rest_PagingRPC.want
- internal/gengapic/testdata/rest_UnaryRPC.want
This adds a `buildHeaders` helper to REGAPIC clients that takes `metadata.MD` from the outgoing `context.Context`, joins it with other `metadata.MD` (like `xGoogMetadata` and the `Content-Type` header), and converts it into an `http.Header` for use on each `http.Request`. This extends the existing code by pulling `metadata.MD` from the outgoing `context.Context` which allows end-users to continue to set metadata/headers the way our GAPIC/gRPC already supports.
The client method builds the `http.Header` once and reuses it for each new `http.Request` built per attempt. This saves a small bit of processing time.
Fixes #855
> feat(gengapic): REGAPIC headers built from metadata

- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengrpc.go
- internal/gengapic/lro.go
Adds a helper that builds the fully-qualified proto element name for a given element, changes some places where it can be used, and removes an extraneous helper `getServiceName` replaced by `fqn` calls. This helper aids me in other code I'm writing.
> chore(gengapic): add fqn helper

- WORKSPACE
- internal/gengapic/BUILD.bazel
- internal/gengapic/client_init_test.go
- internal/gengapic/custom_operation.go
- internal/gengapic/custom_operation_test.go
- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/helpers.go
- internal/gengapic/paging.go
- internal/gengapic/testdata/custom_op_init.want
- internal/gengapic/testdata/custom_op_type.want
- internal/gengapic/testdata/custom_op_type_bool.want
- internal/gengapic/testdata/custom_op_type_enum.want
- internal/gengapic/testdata/rest_CustomOp.want
- repositories.bzl
This is the foundation of Full LRO support for DIREGAPIC/Compute:
* operation service initialization
* operation service-specific operation wrappers
* Poll, Done, Name methods
Missing APIs compared to Standard LRO:
* Cancel (all Compute operation services expose a Delete rpc, but nothing exactly like Cancel)
* Wait (only 3/4 Compute operation services expose a Wait rpc, need to follow up here)
* Metadata (No plans to support)
* Response (No plans to support)
Specifically, the Operation wrapper(s) generated for DIREGAPIC APIs will create a single Operation wrapper type, that embeds an (internal) operationHandle interface consisting of `Proto` and `Poll` methods. Every operation service will get an operationHandle implementation, which will be embedded in Operation wrappers created by RPCs …
> feat(gengapic): implement diregapic lro foundation + polling

- .github/workflows/ci.yaml
- WORKSPACE
- repositories.bzl
This updates the version of `rules_go` used in this WORKSPACE to `v0.30.0` (which ups the min version of bazel to `v4.2.1`) and reverts changes that were once necessary to override the version of `go_genproto` brought in for bazel builds. This also updates the version of Go used in bazel builds to `1.16.5` and switches our bazel job in CI to run with `bazelisk` in order to select bazel v5.0.0. Finally, this updates the bazel deps using `make update-bazel-repos`.
> fix: update rules_go and bazel deps

- internal/gengapic/custom_operation.go
- internal/gengapic/example.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/custom_op_example.want
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/empty_example_grpc.want
- internal/gengapic/testdata/foo_example.want
- internal/gengapic/testdata/foo_example_rest.want
This updates the generated GoDoc examples for DIREGAPIC LRO RPCs to use the operation wrapper returned by the client to `Wait` for operation completion.
This also cleans up/refactors some of the internal helper code/tests.
> feat(gengapic): diregapic lro examples use wrapper

- cmd/protoc-gen-go_cli/test.sh
- internal/gengapic/fuzz.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/helpers.go
- internal/gengapic/helpers_test.go
- internal/gengapic/testdata/method_GetAnotherThing.want
- internal/gengapic/testdata/method_GetEmptyThing.want
- internal/gengapic/testdata/method_GetManyOtherThings.want
- internal/gengapic/testdata/method_GetManyThings.want
- internal/gengapic/testdata/method_GetManyThingsOptional.want
- internal/gengapic/testdata/method_GetOneThing.want
- internal/gengapic/testdata/method_ServerThings.want
- showcase/echo_test.go
- showcase/main_test.go
Add support for the [google.api.routing](https://github.com/googleapis/googleapis/blob/master/google/api/routing.proto) annotation. In short, this annotation allows API producers to explicitly define those request fields should be include in request headers/metadata. Furthermore, it enables API producers to define simple segment matchers (primarily for resource name values) that are generated into regular expressions in the client that extract segments of a field's value to be sent in the header. Finally, it enables API producers to specify a key other than the field name to use in the header key-value-pair. In relation to the implicit headers (extraced from google.api.http annotations), the google.api.routing annotation takes precedence. Please read the annotation documentation for more …
> feat: add dynamic routing header generation

- internal/gengapic/doc_file.go
- internal/gengapic/gengrpc.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/custom_op_init.want
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_alpha_emptyservice.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/doc_file_beta_emptyservice.want
- internal/gengapic/testdata/doc_file_emptyservice.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/lro_client_init.want
This will allow us to override the value after the client has been
generated in an init function. For that code please see
https://github.com/googleapis/google-cloud-go/pull/5687
Previous "UNKNOWN" version behaviour in maintained in a new
function.
> feat: make versionClient a var

- internal/gengapic/doc_file.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/rest_ServerStreamRPC.want
- showcase/echo_test.go
- showcase/go.sum
This adds support for REGAPIC Server Stream RPCs. Since server-stream RPCs in GAPICs must return the gRPC-defined, RPC-specific "stream client" interface, we must implement that interface around the HTTP-JSON stream (the Response Body) opened by the HTTP-JSON request. An RPC-specific implementation of that stream client interface is generated in the GAPIC that utilizes the `gax.ProtoJSONStream` helper to decode the stream contents into the proto messages. The behavior of this generated stream client is the same as documented by the gRPC-defined interface.
When the stream is done/closed, `io.EOF` is returned.
If the `context.Context` used to initialize the stream is canceled, the invocations of `Recv` fail.
When the stream is finished or in the event of an error, the `gax.ProtoJSONStream` …
> feat(gengapic): regapic server-streaming

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/gengrpc.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/lro.go
- internal/gengapic/paging.go
- internal/gengapic/stream.go
- internal/gengapic/testdata/rest_EmptyRPC.want
- internal/gengapic/testdata/rest_ServerStreamRPC.want
- internal/gengapic/testdata/rest_UnaryRPC.want
- showcase/echo_test.go
- showcase/go.sum
Support injection of either implicit (derived from `google.api.http`) or explicit headers (derived from `google.api.routing`) in REGAPICs. Fixes #844 
Minor refactoring to remove unnecessary `error` return types and reduce indentation.
> feat(gengapic): regapic implicit/explicit header injection

- internal/gengapic/genrest.go
- internal/gengapic/testdata/rest_EmptyRPC.want
When an HTTP path param encompassed multiple segements e.g. `{name=blah/blah}`, the `=blah/blah` portion wasn't stripped when attempting to look up the field, which resulted in it being considered a query param in addition to a path param.
> fix(gengapic): REGAPIC fix path param parsing remove duped query param

- internal/gengapic/genrest.go
- internal/gengapic/testdata/rest_LongrunningRPC.want
- internal/gengapic/testdata/rest_ServerStreamRPC.want
- internal/gengapic/testdata/rest_UnaryRPC.want
Part of our REGAPIC effort to standardize JSON (de)serialization of enums as numbers to avoid the "unknown enum" error that comes with using the string identifiers instead.
Note: I've removed the use of `UseProtoNames: false` option because it is `false` by default so stating that explicitly is unnecessary and it was done inconsistently.
> fix(gengapic): REGAPIC encode enums as numbers

- internal/gencli/BUILD.bazel
- internal/gencli/cmd_file.go
- internal/gencli/gencli.go
- internal/gencli/testdata/start-todo.want
I have a generated CLI for an API that just added an LRO with an empty response type:
```
rpc DeleteInstance(DeleteInstanceRequest) returns (google.longrunning.Operation) {
option (google.api.http) = {
delete: "/v1/{name=projects/*/locations/*/instances/*}"
};
option (google.api.method_signature) = "name";
option (google.longrunning.operation_info) = {
response_type: "google.protobuf.Empty"
metadata_type: "OperationMetadata"
};
}
```
Because the response type was empty, the generated grpc `Wait()` and `Poll()` methods returned single values (`error` only), which broke the generated CLI.
This change gets the generated CLI to compile but I have not yet verified the functionality. (I'll follow up when I do)
> Update cli generator to handle LROs with empty response types.

- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/custom_op_init.want
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/empty_opt.want
- internal/gengapic/testdata/foo_opt.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/host_port_opt.want
- internal/gengapic/testdata/iam_override_opt.want
- internal/gengapic/testdata/rest_CustomOp.want
- internal/gengapic/testdata/rest_UnaryRPC.want
- showcase/main_test.go
- showcase/sequence_test.go
This adds generation for default retry config for REGAPIC clients. The status codes in the retry configuration used today for gRPC are converted into HTTP status codes according to a canonical mapping that all languages are using.
Fixes #843.
> feat(gengapic): REGAPIC retry support

- .github/workflows/ci.yaml
- internal/gengapic/fuzz.go
This is necessary to use `apidiff`, the module for which specifies Go 1.18 now.
> chore(ci): update Go to v1.18.3 in ci

- showcase/compliance_test.go
- showcase/main_test.go
Allows us to remove the `showcaseSemver` variable and update the gapic-showcase dependency used in our integration tests via renovate.
> chore(showcase): lookup showcase version in go.mod

- internal/gengapic/generator.go
- internal/gengapic/options.go
- internal/gengapic/options_test.go
- internal/pbinfo/pbinfo.go
- internal/pbinfo/pbinfo_test.go
Per the [protobuf Go docs](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package), there is an option to override the `go_package` option in specific proto files. If this is used during generation of the protobuf/grpc stubs, the GAPIC generator needs to know about it, so that the proper imports can be generated for the request/response/stub types.
> feat(genpapic): support protobuf-go go_package mapping option

- rules_go_gapic/go_gapic.bzl
before: `transport = ["grpc", "rest"]`
after: `transport = "grpc+rest"`,
This is to make it consistent with original design and other rules.
> fix: change go_gapic_library rule  transport argument type from array to string

- showcase/echo_test.go
Bump the `Ttl` used in the Showcase integration test for `Wait` in order to force polling with `GetOperation`.
> chore(showcase): bump Wait test ttl

- WORKSPACE
Tested locally with `make update-bazel-repos`. Should unblock execution of the `deps` workflow. Workaround mentioned in  https://github.com/bazelbuild/bazel-gazelle/issues/1285.
> chore(bazel): include bazel-skylib to fix gazelle

- repositories.bzl
This repo uses rules_gapic for very few things in the go_gapic_library/assembly_pkg implementations, but we should make sure it is up to date.
> chore(bazel): update rules_gapic to 0.14.1

- internal/gengapic/genrest.go
- internal/gengapic/helpers.go
- internal/gengapic/lro.go
- internal/gengapic/mixins.go
- internal/gengapic/mixins_test.go
> fix(gengapic): regapic GetOperation path fallback logic

- internal/gengapic/doc_file.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_alpha_emptyservice.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/doc_file_beta_emptyservice.want
- internal/gengapic/testdata/doc_file_emptyservice.want
> fix(gengapic): fix service-specific constructor name in doc_file.go

- internal/gengapic/markdown.go
- internal/gengapic/markdown_test.go
> fix(gengapic): fix linkParser regexp to support multi-line link tags

- internal/gengapic/example.go
- internal/gengapic/testdata/custom_op_example.want
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_alpha_emptyservice.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/doc_file_beta_emptyservice.want
- internal/gengapic/testdata/doc_file_emptyservice.want
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/empty_example_grpc.want
- internal/gengapic/testdata/foo_example.want
- internal/gengapic/testdata/foo_example_rest.want
See b/240118237 for requirements.
See also:
* [Python](https://github.com/googleapis/gapic-generator-python/pull/1417)
* [Java](https://github.com/googleapis/gapic-generator-java/pull/1029)
> feat(gengapic): add in-line snippet comment to example.go

- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/testdata/rest_UpdateRPC.want
- showcase/compliance_test.go
- showcase/echo_test.go
- showcase/go.mod
- showcase/go.sum
- showcase/identity_test.go
- showcase/main_test.go
- showcase/sequence_test.go
Properly handle protobuf well known message types that have special JSON mappings e.g. `google.protobuf.FieldMask` when they appear as query parameters.
The list of well known types is defined here: https://developers.google.com/protocol-buffers/docs/proto3#json
Update gapic-showcase to v0.25.0 that exercises this code, and update the Identity service tests to run against REST as well, to exercise the FieldMask encoding.
> fix: regapic support for proto wkt in query params

- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/testdata/rest_UpdateRPC.want
For REGAPIC query params, repeated non-message fields should be included in the query params as multiple, individual key-value pairs using the same field name as the key and each item in the slice as a singular value.
Fixes #1160
> fix(gengapic): separate repeated prim qp values

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
Generate interface-level, method documentation for Client and Bi-Di streaming methods when `rest` transport is selected that indicates that the method is unsupported for the REST transport. This should help reduce confusion when the method returns an error saying the same thing.
Note: `m.GetClientStreaming()` covers both streaming types in scope becaus Bi-Di stream is just `ClientStreaming: true` && `ServerStreaming: true`.
> fix(gengapic): document client/bidi streaming unsupported in REST

- internal/gengapic/genrest.go
While fixing the BUILD.bazel files for Go REGAPIC clients, I saw a failure due to an extraneous `protojson` import that our pipeline's `goimports` task was cleaning up. I discovered that it was because of a Unary RPC that didn't have a `body` and returned a `google.api.HttpBody`, which we do not need to unmarshal.
I also moved it into a more precise location for the server streaming handler.
> fix(gengapic): extraneous protojson import

- .github/workflows/ci.yaml
Raises Go runtime version of the `compute-regen` job in order to align with `google-cloud-go` where it tries to run sanity checks. Also runs `go mod tidy` before other `go` tool commands.
> chore(ci): tidy compute job

- internal/gengapic/gengapic.go
- internal/gengapic/helpers.go
- internal/gengapic/helpers_test.go
- test.sh
This is a fix, and introduces the possibility of a breaking change, in generation of clients when `rest` is a selected transport. If a proto service being generated doesn't have any RPCs with `google.api.http` annotations i.e. they are not "REST-able", then a REST client is not generated for the proto service.
I've added a sanity check but based on where the code is placed it is really hard to test without setting up the entire generator in code. I have tested this in local generation and with the known example added to `test.sh`.
> fix(gengapic): only gen REST client for RESTable services

- internal/gengapic/stream.go
- internal/gengapic/testdata/method_ServerThings.want
Inject default call options for server-stream, gRPC calls. This includes default retry options that will work when trying to establish a new stream.
It looks like, unfortunately, this was errantly removed in #577 and it snuck through review.
Addresses the generator issue mentioned in https://github.com/googleapis/google-cloud-go/issues/5906.
> fix(gengapic): inject gRPC server stream call opts

- .github/workflows/assets.yaml
- .github/workflows/ci.yaml
- internal/grpc_service_config/config_test.go
- showcase/main_test.go
Modifies our CI use of the `setup-go` Action to pull the Go version from our `go.mod` file(s).
Removes unnecessary `go mod tidy` step in `compute-regen`.
Fixes some extraneous whitespace that `gofmt` complained about.
> chore(ci): use go verison in go.mod

- .github/workflows/ci.yaml
- .github/workflows/deps.yaml
We recently updated the target bazel version in googleapis to 6.0.0, so let's do the same here.
> chore(ci): use bazel 6

- README.md
- rules_go_gapic/go_gapic.bzl
Temporarily omit snippets during bazel-based generation.
> fix: omit-snippets for bazel

- internal/gengapic/snippets.go
- rules_go_gapic/go_gapic.bzl
* Rename snippet files to `*.go.txt` to avoid bazel compilation.
* Package snippets in `*_go_gapic_srcjar-snippets.srcjar` in `go_gapic.bzl`.
> fix: restore omit-snippets for bazel

- internal/gengapic/example.go
* Without this check, examples may be incomplete.
> fix(gengapic): check error from exampleMethodBody

- .github/workflows/ci.yaml
- internal/gengapic/custom_operation.go
I believe without the deadline code time was no longer being included here or something. Tested locally and the target now compiles again with this change
Also removed the compute regen test as compute can no longer be regenerated with the old tooling.
> fix: add time import for compute operations

- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/mixins.go
- internal/gengapic/mixins_test.go
Fixes filtering out mixin proto files unless generating a mixin gapic explicitly.
The check is now based on if the Go package path for the GAPIC to be generated includes the `iam` `location` or `longrunning` package in it e.g. `cloud.google.com/go/iam/apiv1`. This ensures we can still generate a GAPIC for those mixin services, but prevents them from being accidentally included in a dependent GAPIC.
Refactors some of this code to make it easier to unit test.
> fix(internal/gengapic): fix mixin file filter

- internal/gengapic/example_test.go
- internal/gengapic/snippets.go
- internal/gengapic/snippets_test.go
* Write snippets at the top level of the google-cloud-go namespace.
* With the following change to **each entry**  in `deep-copy-regex` in `.OwlBot.yaml`, both client files and snippets are copied to the correct destinations in google-cloud-go. (`deep-remove-regex` will also need to be updated to remove deleted snippets.)
```diff
-  - source: /google/cloud/asset/v1/cloud.google.com/go/asset/apiv1
-    dest: /asset/apiv1
+  - source: /google/cloud/asset/v1/cloud.google.com/go/
+    dest: /
```
<details>
<summary>Results from `bazelisk build //google/cloud/asset/v1:gapi-cloud-asset-v1-go`</summary>
<pre>
chrisdsmith@chrisdsmith:~/oss/googleapis$ tar -tzf bazel-bin/google/cloud/asset/v1/gapi-cloud-asset-v1-go.tar.gz
./cloud.google.com/
./cloud.google.com/go/
./cloud.google.com/go/asset/ …
> fix(internal/gengapic): write snippet output to cloud.google.com/go

- internal/gengapic/doc_file.go
- internal/gengapic/testdata/doc_file.want
- internal/gengapic/testdata/doc_file_alpha.want
- internal/gengapic/testdata/doc_file_alpha_emptyservice.want
- internal/gengapic/testdata/doc_file_beta.want
- internal/gengapic/testdata/doc_file_beta_emptyservice.want
- internal/gengapic/testdata/doc_file_emptyservice.want
Fixes: https://github.com/googleapis/gax-go/issues/228
> docs: add link to error handling docs in root mod

- renovate.json
- don't assign reviewer, leave it to CO
- extend the base weekly strat
- group deps bumps together.
Let's try bundling dep updagrades so a single pr can do it all for this repo. It may be we want to explicitly package some seperatly, if so we can carve those out in a future pr.
> chore: make renovate config closer to other packages

- internal/gengapic/BUILD.bazel
- internal/gengapic/client_init.go
- internal/gengapic/client_init_test.go
- internal/gengapic/genrest.go
- internal/gengapic/lro.go
- internal/gengapic/testdata/lro_client_conflict.want
We have a service that is not yet released that uses the same RPC name across two services in the same proto package. Our Operation wrapper identifiers are not scoped to a service so this causes issues when generated a client that does this. For now this is for one client, which may change before GA, so a hacky solution is fine. But we should keep this in the back of our minds should we ever v2 our libraries this is something we would want to avoid.
> fix(internal/gengapic): add workaround for operation collision

- internal/gengapic/metadata.go
Fix error:
internal/gengapic/metadata.go:49:2: this value of c is never used (SA4006)
> chore(internal/gengapic): remove unused variable c

- internal/gencli/cmd_file_test.go
- internal/gencli/completion_file_test.go
- internal/gencli/root_file_test.go
- internal/gencli/service_file_test.go
- internal/gengapic/client_init_test.go
- internal/gengapic/custom_operation_test.go
- internal/gengapic/doc_file_test.go
- internal/gengapic/example_test.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest_test.go
- internal/gengapic/metadata_test.go
- internal/gengapic/snippets_test.go
- internal/txtdiff/diff.go
Use `t.Run` to run tests in parallel where relevant. Additionally, remove the `name` argument `txtdiff.Diff` since it isn't being used.
> chore(internal): run tests in parallel

- internal/gengapic/helpers.go
Fix staticcheck error:
internal/gengapic/helpers.go:231:21: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (S1007)
> chore(internal/gengapic): use raw string with regexp.MustCompile

- internal/gencli/BUILD.bazel
- internal/gencli/gencli.go
- internal/gengapic/custom_operation_test.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest_test.go
- internal/gengapic/paging_test.go
- internal/pbinfo/BUILD.bazel
- internal/pbinfo/pbinfo.go
Replace some usage of github.com/golang/protobuf/proto with google.golang.org/protobuf/proto. The [github.com/golang/protobuf](https://pkg.go.dev/github.com/golang/protobuf) module has been deprecated.
For #348
> chore(internal): replace some usage of deprecated github.com/golang/protobuf/proto 

- internal/grpc_service_config/config.go
Fix staticcheck error:
```
internal/grpc_service_config/config.go:124:14: ptypes.Duration is deprecated: Call the dur.AsDuration and dur.CheckValid methods instead. (SA1019)
```
> chore(internal/grpc_service_config): remove deprecated ptypes.Duration

- internal/gengapic/auxiliary.go
Rename `aux.go` to `auxiliary.go` to fix Windows cloning issue.
Updates https://github.com/googleapis/google-cloud-go/issues/8983
> fix(gengapic): rename file aux to auxiliary

- internal/gencli/BUILD.bazel
- internal/gencli/util.go
- internal/gencli/util_test.go
#1420 broke flag generation because `strings.Title` would title-case each segment of a dot-delimited string, where as `cases.Title` does not ([example](https://go.dev/play/p/vMpS1NmChgd)).
Simple fix to ensure each segment, even if dot-delimited, gets title-cased.
> fix(gencli): title case dot delimited segments

- internal/gengapic/example.go
- internal/gengapic/testdata/custom_op_example.want
- internal/gengapic/testdata/empty_example.want
- internal/gengapic/testdata/empty_example_grpc.want
- internal/gengapic/testdata/foo_example.want
- internal/gengapic/testdata/foo_example_rest.want
- internal/gengapic/testdata/snippet_GetManyThings.want
Adds some code to the paging call example that demonstrates accessing the Iterator's underlying RPC specific response type for a page. Since Iterators are generated per-resource, rather than per RPC, the `Response` field has to be generic, but this makes it harder for users to get at the underlying response message if there are other interesting fields.
Fixes #1467
> fix(internal/gengapic): add iter response access example

- repositories.bzl
- rules_go_gapic/go_gapic.bzl
Adds missing otel grpc/http helpers necessary for grpc & http transport wrapper functionality.
Also adds a bunch of `gazelle` `resolve` directives to help fix resolution issues that gazelle has with `otel` modules. According to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/872, there are some weird issues with resolving otel packages between the separate modules and we must explicitly state the resolution mapping in order to actually have the dependency provided to the `gazelle` generated `go_library` targets.
Addresses b/333129802
> fix(bazel): add missing otel deps & resolve patches

- .bazeliskrc
- .github/workflows/ci.yaml
- .github/workflows/deps.yaml
- Makefile
Bazelisk is the preferred "runner" of bazel and more closely aligns with tools we use in googleapis.
> chore(ci): use bazelisk

- internal/snippets/BUILD.bazel
- internal/snippets/snippets_test.go
- internal/testing/sample/sample.go
Refactor TestNewMetadata, TestToMetadataJSON and TestRegionTag in internal/snippets/snippets_test.go to use the internal/testing/sample package.
For https://github.com/googleapis/gapic-generator-go/issues/1512
> chore(internal/snippets,gengapic): use sample values in tests

- internal/testing/sample/BUILD.bazel
- internal/testing/sample/sample.go
- internal/testing/sample/serviceconfig.go
For https://github.com/googleapis/gapic-generator-go/issues/1512
> chore(internal/testing): update ServiceConfig with additional values

- internal/gengapic/client_init_test.go
- internal/gengapic/generator.go
- internal/gengapic/gengapic.go
- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest_test.go
- internal/gengapic/paging_test.go
- internal/testing/sample/sample.go
At the moment, the `g.init` modifies a type `generator`. In many cases, `g` is empty and populated by `g.init`. It is generally more idiomatic to use a `new<thing>` function to construct a new instance of a type, so g.init is replaced with a `newGenerator` function to follow that pattern.
Additionally, errors were not captured in tests for some calls to `g.init`, which are now handled.
> chore(internal/gengapic): refactor g.init to newGenerator

- rules_go_gapic/go_gapic.bzl
If `google.rpc.Status` is actually referenced in the GAPIC code such that an Go import is necessary, we need to provide the dependency. For example, if a paginated RPC paged over `google.rpc.Status` messages as "errors" stored in a system (see internal link http://yaqs/4633584991517802496).
It is easier to add this here than it is to have the BUILD.bazel generator understand which deps are necessary, and when, to each generator - though we may opt for a more holistic dependency generation approach there in the future, making this unnecessary. Adding it there would result in many many `go_gapic_library` targets getting a new dep that isn't actually necessary to compile the GAPIC code.
> fix(internal/gengapic): include status_go_proto gapic dependency

- internal/gengapic/gengapic.go
- internal/gengapic/mixins.go
- internal/gengapic/mixins_test.go
At the moment checkIAMPolicyOverrides both checks if IAMPolicyOverrides is needed and sets the value of g.hasIAMPolicyOverrides which is unexpected.
Rename checkIAMPolicyOverrides to containsIAMPolicyOverrides, and return a boolean value to be set outside the function.
> chore(internal/gengapic): refactor checkIAMPolicyOverrides

- cmd/protoc-gen-go_gapic/main.go
- internal/gengapic/gengapic.go
At the moment, Gen returns a non-nil value when the error is not nil, which is an unexpected Go pattern. Refactor Gen so that it only returns one value, and the Error field is set inside the function.
> chore: refactor Gen error handling

- showcase/showcase.bash
This PR adds an experimental grpc plugin option to the showcase test script, to ensure we get consistent generation when doing A/B apidiff tests.
Related: https://github.com/googleapis/gapic-generator-go/issues/1554
> test: add the use_generic_streams_experimental=false to showcase builds

- internal/gengapic/paging.go
Ref: https://pkg.go.dev/google.golang.org/protobuf/proto#Uint32
> fix: use correct function name

- WORKSPACE
- showcase/showcase.bash
* upgrade bazel_gazelle to 0.38.0
* upgrade com_google_protobuf to 25.4
* add rules_proto 6.0.2
* remove -use_generic_streams_experimental
* fix error: protoc-gen-go-grpc: no such flag -use_generic_streams_experimental
refs: #1554
> chore: upgrade rules_go to 0.49.0

- renovate.json
All of these deps added to the ignoreDeps need to be manually tested in googleapis before bumping. We need to do this intentionally and likely separate from other Go deps.
Also it seems like the grouping was not working, so I removed it for the time being.
> chore: don't update bazel deps

- internal/gencli/gencli.go
- internal/gencli/root_file.go
- internal/gencli/service_file_test.go
- internal/gencli/testdata/root_file.want
- internal/gencli/testdata/service_file.want
Reverts googleapis/gapic-generator-go#1555, which broke gencli generation. The dependency replacement for proto-JSON encoding actually requires an upgrade (it is not a compat api) and the `proto` lib change also requires changes to generated cli code.
Since the gencli isn't a production system and should probably be cleaned up entirely, I'm just reverting this change to unblock development on showcase. What is generated is currently broken.
> fix(internal/gencli): revert broken migration to protobuf-go v2 in gencli

- internal/gengapic/gengapic.go
- internal/gengapic/testdata/helpers_default_scope.want
- internal/gengapic/testdata/helpers_multiple_scopes.want
- internal/gengapic/testdata/helpers_no_scopes.want
The refactor of helper methods from docs.go to helpers.go yielded a double-import, as the previous code yielded the full doc.go directly without leveraging the import management via gengapic's commit mechanism.
This PR removes the static import templating, and transitions to using the import templating available as part of the commit mechanism.
> fix: improve imports behavior for helpers.go

- internal/gengapic/gengapic.go
Fixes bug where some imports are missing if only rest or only grpc transport is specified.
> fix: update logging imports in helpers file

- repositories.bzl
Related: https://github.com/googleapis/gapic-generator-go/issues/1608
> fix: downgrade bazel google.golang.org/protobuf dep

- internal/gengapic/client_init.go
- internal/gengapic/gengapic.go
- internal/gengapic/snippets.go
- internal/snippets/snippets.go
Fixes https://github.com/googleapis/google-cloud-go/issues/12063
Verified that this generates the Pub/Sub snippets correctly running on local copy of googleapis/googleapis
> feat: support service renaming for snippets

- internal/gengapic/gengapic.go
- internal/gengapic/gengrpc.go
- internal/gengapic/genrest.go
- internal/gengapic/testdata/custom_op_init.want
- internal/gengapic/testdata/deprecated_client_init.want
- internal/gengapic/testdata/empty_client_init.want
- internal/gengapic/testdata/foo_client_init.want
- internal/gengapic/testdata/foo_rest_client_init.want
- internal/gengapic/testdata/helpers_default_scope.want
- internal/gengapic/testdata/helpers_multiple_scopes.want
- internal/gengapic/testdata/helpers_no_scopes.want
- internal/gengapic/testdata/lro_client_init.want
- internal/gengapic/testdata/service_rename.want
We are adding the version of google.golang.org/protobuf that we are using in the x-goog header. The library currently only exposes their minor version. If they ever take a v2 we will need to update this code accordingly and/or ask them to expose the major version as well.
MaxVersion is documented as: "It is always the current version of the module."
Internal Bug: 415822167
> feat: add proto runtime version in header

- WORKSPACE
- showcase/go.mod
Needed for some deps. Also updated bazel workspaces Go version as this will be needed for building the code.
> chore: update showcase to go 1.23

- internal/gengapic/gengapic_test.go
- internal/gengapic/genrest.go
- internal/gengapic/genrest_test.go
- internal/gengapic/lro.go
- internal/gengapic/testdata/method_EmptyLRO.want
- internal/gengapic/testdata/rest_LongrunningRPC.want
- showcase/compliance_test.go
When adding the auto-populated fields feature in [feat(gengapic): add support for AutoPopulatedFields UUID4 #1460](https://github.com/googleapis/gapic-generator-go/pull/1460), based on the spec below (from  go/client-populate-request-id-design), I did not support auto-populated fields in the generation of long-running operation (LRO) RPCs. This was a mistake. I confirmed today with @noahdietz that LROs should indeed be treated as unary RPCs for this feature.
> Client library generators **should** enable automatic population of request fields at the time of sending the request in the specified format if and only if all of the following conditions hold:
>
>  * The field is a top-level string field of a unary method's request message.
>  * ...
> fix(gengapic): add support for AutoPopulatedFields UUID4 to LROs

- internal/gengapic/generator.go
- internal/gengapic/gengrpc.go
- internal/gengapic/testdata/foo_opt.want
Given storagecontrol being the only use case we know, hard-coding it in the generator seems the most convenient approach.
To uniquely identity the service, it uses the API and service name joined by "/".
> feat(gengapic): conditionally enable directpath for storagecontrol
